<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_add_wishlist</name>
   <tag></tag>
   <elementGuidId>4c6d3ee6-6e30-472a-8570-59fa9b38f843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add-to-wishlist-button-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-to-wishlist-button-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cb0f49f-371b-4a19-8c02-feaa56f90e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>087f30ab-8fcf-4125-81b6-2345345c292c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-to-wishlist-button-2</value>
      <webElementGuid>aacd24af-b24d-4daa-a57c-1cea838ca59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-2 add-to-wishlist-button</value>
      <webElementGuid>4d54fc25-a172-4809-ad29-b9a1c8f28024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add to wishlist</value>
      <webElementGuid>8caeb2b4-06aa-4b0d-aa87-3ac473d42c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productid</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e8075d86-3c39-4593-a97f-bb06401efe1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AjaxCart.addproducttocart_details('/addproducttocart/details/2/2', '#product-details-form');return false;</value>
      <webElementGuid>b714af12-ba0c-4927-9927-a66ffc25e5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-wishlist-button-2&quot;)</value>
      <webElementGuid>1b64ed32-cfdc-4934-8a15-62bebc8e3660</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add-to-wishlist-button-2']</value>
      <webElementGuid>5ce128b0-3e67-4f81-a82f-c2a6196b822a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/div/input[3]</value>
      <webElementGuid>7081b908-d500-483f-9ac9-4d6281232963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>9e9a0c17-ef62-467f-9509-af4afc4d753a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'add-to-wishlist-button-2']</value>
      <webElementGuid>4e59d09e-a14d-4a52-baa8-56ccdf0c1731</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
