<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_sender_name</name>
   <tag></tag>
   <elementGuidId>7a40f01c-d39c-497e-9506-2820eb8ebd1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='giftcard_2_SenderName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#giftcard_2_SenderName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49f8ccba-f49c-4362-9297-69b0727ff2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sender-name</value>
      <webElementGuid>aba66f38-fad2-4ff2-8be2-c080f70a73b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>giftcard_2_SenderName</value>
      <webElementGuid>b35b05bc-fe23-4f10-ba47-adbba57bc4f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>giftcard_2.SenderName</value>
      <webElementGuid>e1090d44-9228-4ae4-abf3-fb492d3e41ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a9974eb3-4b3d-4b97-a503-646675ce6cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>wayan wayan</value>
      <webElementGuid>1a2daf30-91b3-4c8d-87c0-29854274e12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;giftcard_2_SenderName&quot;)</value>
      <webElementGuid>b82e9f8f-e8ae-442f-9693-dc641c998810</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='giftcard_2_SenderName']</value>
      <webElementGuid>2cd761ae-ba93-4163-a196-018fb5c7df87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[4]/div[3]/input</value>
      <webElementGuid>b087ab94-1f82-4254-b33a-524f87c6e291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>b7b19fcb-8df1-4b79-8a08-21193a7375ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'giftcard_2_SenderName' and @name = 'giftcard_2.SenderName' and @type = 'text']</value>
      <webElementGuid>6cba4769-33f5-4411-aed0-7cd8f081324c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
