<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_recipient_name</name>
   <tag></tag>
   <elementGuidId>23856119-1627-4498-882c-7ba86ef878c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#giftcard_2_RecipientName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='giftcard_2_RecipientName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17298eb9-9dd0-47a9-87c9-cfb5437ae742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>recipient-name</value>
      <webElementGuid>d3acb9ee-4963-4ae9-ba40-4ce21010d84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>giftcard_2_RecipientName</value>
      <webElementGuid>5cb7f83f-ddc2-4041-be3f-e4f6dbaf9fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>giftcard_2.RecipientName</value>
      <webElementGuid>792f83a9-30f4-42de-8bbc-52442b5cc059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b2e4a0c0-fe37-4a7a-841a-8b9aead115c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;giftcard_2_RecipientName&quot;)</value>
      <webElementGuid>7e2656db-8c55-4e04-99eb-d8cc1a6ba913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='giftcard_2_RecipientName']</value>
      <webElementGuid>18c4ec8c-a3ff-45af-8a13-bd29ee756ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[4]/div/input</value>
      <webElementGuid>3d8b34c3-30f4-4e11-8b60-97501704c832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>9ab6e131-462b-4200-ad66-5e070eebd663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'giftcard_2_RecipientName' and @name = 'giftcard_2.RecipientName' and @type = 'text']</value>
      <webElementGuid>9e558eb6-2428-4c66-89fe-9e26a05b0f78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
