<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_recipient_email</name>
   <tag></tag>
   <elementGuidId>44aa7273-ca74-492c-a568-c750fb65a47c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='giftcard_2_RecipientEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#giftcard_2_RecipientEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e89f78f-da0d-4537-8238-8a3475ed4f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>recipient-email</value>
      <webElementGuid>e75367fb-961d-4d94-8b51-d93b831befdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>giftcard_2_RecipientEmail</value>
      <webElementGuid>4d50f01b-2a05-4e26-aac8-30419a53c85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>giftcard_2.RecipientEmail</value>
      <webElementGuid>d9ae78a4-bbc5-437a-b411-55081062cdde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4f75ce57-fe6f-44dc-9c78-b96e1d267933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;giftcard_2_RecipientEmail&quot;)</value>
      <webElementGuid>ffc9eb41-a7cc-44dd-a9b8-afb2832b4b77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='giftcard_2_RecipientEmail']</value>
      <webElementGuid>52e5bc3e-4872-49de-a90a-6d0b9151bb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[4]/div[2]/input</value>
      <webElementGuid>3c5ef4af-ed0d-4062-930a-28e18d48db58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>c23015ff-c0fc-4c54-8ea6-cf8fb0a7f795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'giftcard_2_RecipientEmail' and @name = 'giftcard_2.RecipientEmail' and @type = 'text']</value>
      <webElementGuid>d1712a5a-25a7-4fc1-b0d6-4d7d7c4366ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
