<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_sender_email</name>
   <tag></tag>
   <elementGuidId>5ba02138-97b4-4acb-bde2-f0c342b06d94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='giftcard_2_SenderEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#giftcard_2_SenderEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a410c45-ddc8-4041-a0d6-4b79348d9c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sender-email</value>
      <webElementGuid>6916fb59-7dd3-4545-b849-2cbba07b981f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>giftcard_2_SenderEmail</value>
      <webElementGuid>e79702fa-b1a4-4c05-a44c-44fd55008245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>giftcard_2.SenderEmail</value>
      <webElementGuid>40733cb0-30ca-494b-afe6-d45e4f316be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98e05e7c-6a06-42d8-b048-fa35a03922af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>wayanpnm@gmail.com</value>
      <webElementGuid>04a1a5e0-d19c-48d1-b592-7501812be6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;giftcard_2_SenderEmail&quot;)</value>
      <webElementGuid>f79211af-9dbf-469f-b188-ba2d3b25df86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='giftcard_2_SenderEmail']</value>
      <webElementGuid>e5b1b377-4e34-41c5-a3ea-4292521fa67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[4]/div[4]/input</value>
      <webElementGuid>a7599772-bced-44ff-badf-0ce8e47175a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>fee3720b-0a06-4b60-a447-1a91c355ff60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'giftcard_2_SenderEmail' and @name = 'giftcard_2.SenderEmail' and @type = 'text']</value>
      <webElementGuid>a170e042-fae2-4ba8-88b1-488ca3942805</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
