<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_billing_address</name>
   <tag></tag>
   <elementGuidId>7287f38b-3741-489d-a8c6-0537d42e94ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='opc-billing']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.step-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ee031c3-f835-453a-ae8d-7dabeda012e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>step-title</value>
      <webElementGuid>d647d461-af44-470d-8e99-876ec3838215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    1
                    Billing address
                </value>
      <webElementGuid>86995329-ea75-474b-84a1-105cff846f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc-billing&quot;)/div[@class=&quot;step-title&quot;]</value>
      <webElementGuid>249a5cbf-9f07-4766-94b0-b1d544f6a4af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='opc-billing']/div</value>
      <webElementGuid>2cb6ca67-ad19-4ba0-8086-371531b33404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::div[2]</value>
      <webElementGuid>68ff8a35-70f3-4deb-b5a7-8ad38c075297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gift Cards'])[2]/following::div[9]</value>
      <webElementGuid>00cf63dc-3c64-417c-8f23-cbb27b78fe16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First name:'])[1]/preceding::div[1]</value>
      <webElementGuid>e0e65dd6-a1ce-419a-83cd-e114139ccc89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/div</value>
      <webElementGuid>e03653e5-afc6-4ff1-a7be-ce975bc05506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                    1
                    Billing address
                ' or . = '
                    1
                    Billing address
                ')]</value>
      <webElementGuid>70018ed4-2611-4203-bd0d-980e9ec3ff4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
