<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_shopping_cart</name>
   <tag></tag>
   <elementGuidId>8ad819a5-c04f-4ead-a5fd-f87dc999aca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ico-cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='topcartlink']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2e2bb3aa-cc62-4308-b223-6bf9986f6b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cart</value>
      <webElementGuid>4f91df4e-5701-410f-8c84-0faf9e668dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico-cart</value>
      <webElementGuid>232ed3ef-0a87-4bbf-8519-b283990fefde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Shopping cart
                    (0)
                </value>
      <webElementGuid>f660dc5c-58b5-48d8-a0ce-cd809074abb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topcartlink&quot;)/a[@class=&quot;ico-cart&quot;]</value>
      <webElementGuid>fdc9db42-b22c-4b9d-b5c1-4576f63e8d7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='topcartlink']/a</value>
      <webElementGuid>8fe114e3-a700-43d1-a424-4764623e3dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::a[1]</value>
      <webElementGuid>13fefca8-ed5f-4b97-af32-53a361921d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::a[2]</value>
      <webElementGuid>b379623c-c330-4aac-90f6-79e540b83da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cart')]</value>
      <webElementGuid>02bb5ae0-82d9-4cb8-9acf-130f8d101e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>5c0d0412-568a-4aee-8790-6edcfaad2b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cart' and (text() = '
                    Shopping cart
                    (0)
                ' or . = '
                    Shopping cart
                    (0)
                ')]</value>
      <webElementGuid>67ad1206-3446-44b3-9d69-615d68ad5006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
