<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal_term_of_service</name>
   <tag></tag>
   <elementGuidId>406a14b2-edf8-4549-b576-dc932eae060d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='terms-of-service-warning-box']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#terms-of-service-warning-box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>28efdfa1-425e-4866-9a67-2c4dbb298cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms-of-service-warning-box</value>
      <webElementGuid>e37af06f-be2c-4779-844f-73993df1b7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-dialog-content ui-widget-content</value>
      <webElementGuid>f2ef9fea-6419-417e-ba75-818aed61f35d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Please accept the terms of service before the next step.
                        </value>
      <webElementGuid>0c1b415e-56b6-4fe7-a9a3-e2cb221ceceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms-of-service-warning-box&quot;)</value>
      <webElementGuid>19cd3464-b93e-44ac-8107-dcac0f6f3d88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='terms-of-service-warning-box']</value>
      <webElementGuid>cb74f304-012f-4998-ba30-4cd9d3ada01c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[1]/following::div[1]</value>
      <webElementGuid>5e92c1a6-1180-4ad5-89f9-92336ec4b58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of service'])[1]/following::div[1]</value>
      <webElementGuid>0601a5df-6341-4c7d-b16a-ccf5f040c90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]</value>
      <webElementGuid>31bbf433-5479-44bb-9682-b41075bc40b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'terms-of-service-warning-box' and (text() = '
                            Please accept the terms of service before the next step.
                        ' or . = '
                            Please accept the terms of service before the next step.
                        ')]</value>
      <webElementGuid>f05a50c5-44ef-4ccc-b88f-30416f59d786</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
