<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn_payment_cod</name>
   <tag></tag>
   <elementGuidId>2f7073fe-ab16-4025-9e7e-fb6f35d62045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paymentmethod_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#paymentmethod_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>563c87f4-b091-4568-bd4d-4510e8e5c516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentmethod_0</value>
      <webElementGuid>e719502c-43d1-475e-9a78-2f46820bd0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>061f43e4-1fa9-474d-acd1-d4dc05cb77f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentmethod</value>
      <webElementGuid>574ff4e5-5422-4deb-abdc-7efbeb452968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Payments.CashOnDelivery</value>
      <webElementGuid>2c9b1754-bfe9-4c71-a82a-13c3199c7c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>0fc5922c-3c1f-49b5-b8a7-2e7ce7521c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentmethod_0&quot;)</value>
      <webElementGuid>52bfee89-556d-4d32-a7c2-365bf53f440b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paymentmethod_0']</value>
      <webElementGuid>42e75abc-5e35-4d8c-8726-480f4cd8074e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-method-load']/div/div/ul/li/div/div[2]/input</value>
      <webElementGuid>62bb7720-69af-4a71-8508-54a0f3b1ad73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div[2]/input</value>
      <webElementGuid>971041aa-350c-48c3-a6aa-af844fc81357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'paymentmethod_0' and @type = 'radio' and @name = 'paymentmethod' and @checked = 'checked']</value>
      <webElementGuid>b64b238b-4e52-4901-8f2d-6cecf6d61afa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
