<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_purchase_number</name>
   <tag></tag>
   <elementGuidId>c812084d-63d5-4ee8-9d98-4fc45851b664</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PurchaseOrderNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PurchaseOrderNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e9b7b6b-afff-47ec-8d0b-49a8de757bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c7e7c96a-dd4a-4869-b935-c7b06256758a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PurchaseOrderNumber</value>
      <webElementGuid>5cc47835-a51a-4142-82f1-40a2a920c5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PurchaseOrderNumber</value>
      <webElementGuid>7968f417-0d29-45a6-83e7-50f6109a6902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7aa2257e-3c5a-455d-95bc-9554f4c2641f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>a11a56f8-0578-443c-924c-75177c54b6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PurchaseOrderNumber&quot;)</value>
      <webElementGuid>5ed42a7a-a5f7-4478-99f1-525e650cb3d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PurchaseOrderNumber']</value>
      <webElementGuid>ed564d92-af2d-4b41-895f-f52fc6ac469a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-info-load']/div/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>bf16b320-a910-42c9-8596-273a6f850a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>e2e2cfcb-a56c-49bb-8d45-cc8967da055d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PurchaseOrderNumber' and @name = 'PurchaseOrderNumber' and @type = 'text']</value>
      <webElementGuid>8a98cb51-2590-4491-9978-be300aff58ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
