<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_rememberme</name>
   <tag></tag>
   <elementGuidId>49a47e32-bf4d-4529-bcf6-ae5e9f6b0b22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RememberMe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RememberMe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>665792c3-5516-4503-909c-252a5158f19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RememberMe</value>
      <webElementGuid>43a2bbd5-5596-4690-a036-6e6ef61f04ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RememberMe</value>
      <webElementGuid>a87ce067-005f-441b-af82-e13b041fbf8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>75a2200b-63b6-440e-8a5c-b1db47283618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>38dba5f1-36f5-4df8-ab91-1a21f59ce35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RememberMe&quot;)</value>
      <webElementGuid>a205480c-0d2a-49ec-810b-cbeae171d6fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RememberMe']</value>
      <webElementGuid>f01db040-6072-45e0-b741-f1be795ec320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>d9e8ed44-c556-42f7-a8b0-1e0fa3a35920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'RememberMe' and @name = 'RememberMe' and @type = 'checkbox']</value>
      <webElementGuid>4ae639d3-be62-44f9-905c-811ddbfd99f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
