<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gender_Gender</name>
   <tag></tag>
   <elementGuidId>e413925f-269c-42ad-b76f-7eeef2efb275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gender-male']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gender-male</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bacb0f4f-8de8-490a-bb20-7735c9640257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gender-male</value>
      <webElementGuid>ba457e21-3a7b-4cf5-8946-f5c3f6f4c11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Gender</value>
      <webElementGuid>dd12545b-c63c-4ea6-aecb-ca9c020e64e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>67e1143b-1ab5-48b0-b545-110ae56cc232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>ac76870e-682a-4782-bc8f-9bfd844734ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gender-male&quot;)</value>
      <webElementGuid>356935ff-f011-4bff-93ef-61c966919c69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gender-male']</value>
      <webElementGuid>2ce0795a-ff67-4c53-bd61-915e0e20d5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>2c4b961d-326e-4108-aa58-d102b2049c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gender-male' and @name = 'Gender' and @type = 'radio']</value>
      <webElementGuid>6e07ecbc-b4c8-40d2-bfee-6ff4e8362dc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
