<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>login_case</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3ff046b7-2bad-4810-9b10-345e12a84be2</testSuiteGuid>
   <testCaseLink>
      <guid>cceebb24-565d-475b-9a2e-8ced2e19c787</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login/normal/login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>37bd3e88-b2f4-439d-82ea-c9e314244dfe</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/login/login_data_normal</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>37bd3e88-b2f4-439d-82ea-c9e314244dfe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>e304ab20-75bd-4784-9ffc-ea5ea64c8c18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>37bd3e88-b2f4-439d-82ea-c9e314244dfe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>23ba08e2-6b4e-4a6a-988e-c2be688aa80e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d7b3d2e-ed66-4b54-bcbc-8a576d873ceb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login/normal/login_normal</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c31dd5a4-08ef-40e7-9c98-9010e5b76730</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/login/login_data_normal</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c31dd5a4-08ef-40e7-9c98-9010e5b76730</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>e46a107f-6d64-473f-b170-e4193edfb1ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c31dd5a4-08ef-40e7-9c98-9010e5b76730</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>88353ba7-b81c-4731-8271-c88fe159f460</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b82d119-22c3-4de5-a3e2-6b5efb4cfe03</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login/abnormal/login_without_password</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d8b2d0ba-12a2-45a7-9723-2df7d574e3ab</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/login/login_data_normal</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d8b2d0ba-12a2-45a7-9723-2df7d574e3ab</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>2c9233fb-18d4-44f8-b5ab-b39371aec1c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d8b2d0ba-12a2-45a7-9723-2df7d574e3ab</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>cd6aee17-9dd2-4a64-a5dc-dcc646a6474a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a718c5b4-dab8-46c3-9f72-a17d3e6f471a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login/abnormal/login_without_name</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>13051bf8-3dc0-44cf-9d3c-922553a925e5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/login/login_data_normal</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>13051bf8-3dc0-44cf-9d3c-922553a925e5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>1428ac24-a05c-4f0a-b7c8-c6b126bd0fc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>13051bf8-3dc0-44cf-9d3c-922553a925e5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>ada16db6-6dcf-434b-8f3f-8c57718ca961</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
